/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafxswingapplication1;

/**
 *
 * @author benej
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Cracker PRO");

        cod.setToolTipText("");
        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setLabel("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cod)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String S1 = "x";
        String S2 = "x";
        String S3 = "x";
        String S4 = "x";
        String S5 = "x";
        String S6 = "x";
        String S7 = "x";
        String S8 = "x";
        String S9 = "x";
        String S10 = "x";
        String S11 = "x";
        String S12 = "x";
        String S13 = "x";
        String S14 = "x";
        String S15 = "x";
        String S16 = "x";
        String S17 = "x";
        String S18 = "x";
        String S19 = "x";
        String S20 = "x";
        String S21 = "x";
        String S22 = "x";
        String S23 = "x";
        String S24 = "x";

        String C1 = (cod.getText()).substring(0, 1); // 0. o
        if (null != C1) {
            switch (C1) {
                case "0":
                    S5 = "0";
                    S11 = "1";
                    break;
                case "1":
                    S5 = "1";
                    S11 = "0";
                    break;
                case "2":
                    S5 = "2";
                    S11 = "3";
                    break;
                case "3":
                    S5 = "3";
                    S11 = "2";
                    break;
                case "4":
                    S5 = "4";
                    S11 = "5";
                    break;
                case "5":
                    S5 = "5";
                    S11 = "4";
                    break;
                case "6":
                    S5 = "6";
                    S11 = "7";
                    break;
                case "7":
                    S5 = "7";
                    S11 = "6";
                    break;
                case "8":
                    S5 = "8";
                    S11 = "9";
                    break;
                case "9":
                    S5 = "9";
                    S11 = "8";
                    break;
            }
        }
        String C2 = (cod.getText()).substring(0, 2); // 0. o
        if (null != C2) {
            switch (C2) {
                case "0":
                    S6 = "F";
                    S11 = "A";
                    break;
                case "1":
                    S6 = "E";
                    S11 = "B";
                    break;
                case "2":
                    S6 = "D";
                    S11 = "8";
                    break;
                case "3":
                    S6 = "C";
                    S11 = "9";
                    break;
                case "4":
                    S6 = "B";
                    S11 = "E";
                    break;
                case "5":
                    S6 = "A";
                    S11 = "F";
                    break;
                case "6":
                    S6 = "9";
                    S11 = "C";
                    break;
                case "7":
                    S6 = "8";
                    S11 = "D";
                    break;
                case "8":
                    S6 = "7";
                    S11 = "2";
                    break;
                case "9":
                    S6 = "6";
                    S11 = "3";
                    break;
                case "A":
                    S6 = "5";
                    S11 = "0";
                    break;
                case "B":
                    S6 = "4";
                    S11 = "1";
                    break;
                case "C":
                    S6 = "3";
                    S11 = "6";
                    break;
                case "D":
                    S6 = "2";
                    S11 = "7";
                    break;
                case "E":
                    S6 = "1";
                    S11 = "4";
                    break;
                case "F":
                    S6 = "0";
                    S11 = "5";
                    break;
            }
            String C3 = (cod.getText()).substring(0, 3); // 0. o
            if (null != C3) {
                switch (C3) {
                    case "0":
                        S13 = "0";
                        S7 = "0";
                        break;
                    case "1":
                        S13 = "1";
                        S7 = "1";
                        break;
                    case "2":
                        S13 = "2";
                        S7 = "2";
                        break;
                    case "3":
                        S13 = "3";
                        S7 = "3";
                        break;
                    case "4":
                        S13 = "4";
                        S7 = "4";
                        break;
                    case "5":
                        S13 = "5";
                        S7 = "5";
                        break;
                    case "6":
                        S13 = "6";
                        S7 = "6";
                        break;
                    case "7":
                        S13 = "7";
                        S7 = "7";
                        break;
                    case "8":
                        S13 = "8";
                        S7 = "8";
                        break;
                    case "9":
                        S13 = "9";
                        S7 = "9";
                        break;
                }
            }
            String C4 = (cod.getText()).substring(0, 4); // 0. o
            if (null != C4) {
                switch (C4) {
                    case "0":
                        S8 = "F";
                        break;
                    case "1":
                        S8 = "E";
                        break;
                    case "2":
                        S8 = "D";
                        break;
                    case "3":
                        S8 = "C";
                        break;
                    case "4":
                        S8 = "B";
                        break;
                    case "5":
                        S8 = "A";
                        break;
                    case "6":
                        S8 = "9";
                        break;
                    case "7":
                        S8 = "8";
                        break;
                    case "8":
                        S8 = "7";
                        break;
                    case "9":
                        S8 = "6";
                        break;
                    case "A":
                        S8 = "5";
                        break;
                    case "B":
                        S8 = "4";
                        break;
                    case "C":
                        S8 = "3";
                        break;
                    case "D":
                        S8 = "2";
                        break;
                    case "E":
                        S8 = "1";
                        break;
                    case "F":
                        S8 = "0";
                        break;
                }
            }
        }

       // feitas coluna 5 , 11, 6, 12, 13, 7,8

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
